# Generated by Django 4.2.2 on 2023-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichasapp', '0002_alter_rol_name_alter_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Funcionario', 'Funcionario'), ('Usuario', 'Usuario')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
