# Generated by Django 3.2.12 on 2023-06-14 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichasapp', '0003_alter_usuario_rol_delete_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_paciente', models.CharField(max_length=13)),
                ('acompannante', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('previcion_salud', models.CharField(max_length=13)),
                ('domicilio', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=100)),
                ('indicaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichasapp.especialidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichasapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('ocupada', models.BooleanField()),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichasapp.personalsalud')),
            ],
        ),
        migrations.CreateModel(
            name='DatosAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paologia_ges', models.CharField(max_length=100)),
                ('diagnostico_principal', models.CharField(max_length=100)),
                ('disgnotico_complementario', models.TextField()),
                ('presion', models.CharField(default='', max_length=100)),
                ('temperatura', models.CharField(default='', max_length=100)),
                ('peso', models.CharField(default='', max_length=100)),
                ('satO2', models.CharField(default='', max_length=100)),
                ('pulso', models.CharField(default='', max_length=100)),
                ('alergias', models.CharField(default='', max_length=100)),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichasapp.cita')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichasapp.horas'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichasapp.personalsalud'),
        ),
    ]
