# Generated by Django 4.2.2 on 2023-06-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichasapp', '0003_alter_usuario_rol_delete_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('previcion_salud', models.CharField(max_length=13)),
                ('domicilio', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=50)),
            ],
        ),
    ]
