# Generated by Django 3.2.12 on 2023-06-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichasapp', '0004_auto_20230614_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='previcion_salud',
        ),
        migrations.AddField(
            model_name='ficha',
            name='prevision_salud',
            field=models.CharField(choices=[('Fonasa', 'Fonasa'), ('Isapre', 'Isapre')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='tipo_isapre',
            field=models.CharField(choices=[('Colmena', 'Colmena'), ('CruzBlanca', 'CruzBlanca'), ('Consalud', 'Consalud'), ('MasVda', 'MasVda'), ('BanMedica', 'BanMedica')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Intersexual', 'Intersexual')], max_length=200, null=True),
        ),
    ]
