# Generated by Django 3.2.12 on 2023-06-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichasapp', '0005_auto_20230623_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fichasapp.horas'),
        ),
        migrations.AlterField(
            model_name='datosatencion',
            name='id_cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fichasapp.cita'),
        ),
    ]
