# Generated by Django 4.2.2 on 2023-06-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichasapp', '0006_alter_ficha_prevision_salud_alter_ficha_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='tipo_isapre',
            field=models.CharField(choices=[('Colmena', 'Colmena'), ('CruzBlanca', 'CruzBlanca'), ('Consalud', 'Consalud'), ('MasVda', 'MasVda'), ('BanMedica', 'BanMedica')], max_length=200, null=True),
        ),
    ]
