# Generated by Django 3.2.12 on 2023-05-31 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_ficha_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_paciente', models.CharField(max_length=13)),
                ('acompannante', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('especialidad_escogida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.especialidad')),
                ('id_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.ficha')),
                ('id_horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.horas')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.personalsalud')),
            ],
        ),
    ]
