# Generated by Django 3.2.12 on 2023-05-31 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='id_ficha',
        ),
    ]
