# Generated by Django 3.2.12 on 2023-05-31 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_remove_cita_id_ficha'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('paologia_ges', models.CharField(max_length=100)),
                ('diagnostico_principal', models.CharField(max_length=100)),
                ('disgnotico_complementario', models.TextField()),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('presion', models.CharField(max_length=100)),
                ('temperatura', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('satO2', models.CharField(max_length=100)),
                ('pulso', models.CharField(max_length=100)),
                ('alergias', models.CharField(max_length=100)),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.cita')),
            ],
        ),
    ]
