# Generated by Django 3.2.12 on 2023-06-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0005_antecedentes_datosatencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=100)),
                ('indicaciones', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cita',
            name='especialidad_escogida',
        ),
        migrations.RemoveField(
            model_name='datosatencion',
            name='title',
        ),
        migrations.AddField(
            model_name='datosatencion',
            name='alergias',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datosatencion',
            name='peso',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datosatencion',
            name='presion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datosatencion',
            name='pulso',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datosatencion',
            name='satO2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='datosatencion',
            name='temperatura',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Antecedentes',
        ),
    ]
