# Generated by Django 3.2.12 on 2023-06-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0006_auto_20230602_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='horas',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='horas',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
