# Generated by Django 4.2.2 on 2023-07-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acompannante', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('rut', models.CharField(error_messages={'unique': 'This email has already been registered.'}, max_length=13, null=True, unique=True)),
                ('correo', models.EmailField(max_length=50, null=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichasapp.rol')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='fichasapp.especialidad')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='fichasapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('ocupada', models.BooleanField(default=False)),
                ('id_medico', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='fichasapp.personalsalud')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateTimeField()),
                ('prevision_salud', models.CharField(choices=[('Fonasa', 'Fonasa'), ('Isapre', 'Isapre')], max_length=200, null=True)),
                ('tipo_isapre', models.CharField(choices=[('Colmena', 'Colmena'), ('CruzBlanca', 'CruzBlanca'), ('Consalud', 'Consalud'), ('MasVida', 'MasVida'), ('BanMedica', 'BanMedica')], default=None, max_length=200, null=True)),
                ('domicilio', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Intersexual', 'Intersexual')], max_length=200, null=True)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='fichasapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DatosAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patologia_ges', models.CharField(default=None, max_length=100)),
                ('diagnostico_principal', models.CharField(default=None, max_length=100)),
                ('disgnotico_complementario', models.CharField(default=None, max_length=100)),
                ('presion', models.CharField(default=None, max_length=100)),
                ('temperatura', models.CharField(default=None, max_length=100)),
                ('peso', models.CharField(default=None, max_length=100)),
                ('satO2', models.CharField(default=None, max_length=100)),
                ('pulso', models.CharField(default=None, max_length=100)),
                ('alergias', models.CharField(default=None, max_length=100)),
                ('tratamiento', models.CharField(default='Tratamiento', max_length=100)),
                ('id_cita', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='fichasapp.cita')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='id_horario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='fichasapp.horas'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_medico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='fichasapp.personalsalud'),
        ),
        migrations.AddField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='fichasapp.usuario'),
        ),
    ]
